### ISSUE TITLE
Switch from epydoc documentation format

### ISSUE THREAD

**Issue by tomato42** [tomato42/tlslite-ng#14]
Since epydoc is mostly abandoned now, and we use relative imports, which in turn require a patched version of epydoc.

All of this makes setup for contributing harder.

**Comment by tomato42** [comment]
possible tool to automate the process: https://github.com/dadadel/pyment

**Comment by FiachAntaw** [comment]
Two options that come to mind are sphinx and pdoc. Sphinx appears to be the defacto standard for Python projects but would take a lot of effort to get working given that it's designed for separate code/documentation. pdoc is presented as an epydoc successor and so might be a better fit, but seems less flexible than Sphinx (I don't see an easy way to integrate tutorials/examples/other non-specific documentation into the produced API docs).

Would it be better to have a integrated usage/API documentation or just have API-specific documentation and continue to put usage information in the readme?

**Comment by The-Mule** [comment]
I would definitely vote for second option - keep documenting API within the code and put all other documentation to README for now.

**Comment by tomato42** [comment]
`pyment` seems to support Sphinx (the one that I was thinking of using), but then I have no idea what kind of documentation I'll get from it for the stuff we have in code.

But then there are API docs with Sphinx, like this: https://docs.python.org/3/library/json.html#basic-usage so it should be possible. No idea what it requires from the docs sources though...
