### ISSUE TITLE
Unknown group parameters when using SRP with OpenSSL server

### ISSUE THREAD

**Issue by bwintcig** [tomato42/tlslite-ng#145]
When trying to use the tlslite-ng client to connect to an OpenSSL server setup to use SRP with or without a certificate, tlslite-ng throws the Unknown group parameters exception. Testing TLS-SRP with a tlslite-ng server and client it works fine. Has tlslite-ng been tested with other SRP implementations?

I'm using the following to run OpenSSL (version 1.1.0b):
openssl s_server -nocert -cipher SRP -srpvfile password.srpv -www

**Comment by tomato42** [comment]
yes, I tested it with OpenSSL 1.0.1 IIRC

it could be because OpenSSL sends SRP with prime from https://tools.ietf.org/html/rfc7919 instead of primes from https://tools.ietf.org/html/rfc5054

could you packet capture the server key exchange message that openssl sends and paste it here?

**Comment by tomato42** [comment]
actually, I found one issue with the parameters in tlslite-ng, the 3072-bit group from RFC 5054 has an invalid generator - 2 instead of 5. So if the parameters selected by server are based on this group, they will be incorrectly rejected by the client.

**Comment by bwintcig** [comment]
This is what I was able to capture. I'm not sure what TLS SRP traffic is supposed to look like compared to normal TLS traffic. Hopefully this helps, if not, let me know if there's any other data I can provide.

[tlssrp.zip](https://github.com/tomato42/tlslite-ng/files/586320/tlssrp.zip)

**Comment by tomato42** [comment]
so, while server does send a correct prime (RFC 5054 group 5) it does send a bit of a weird generator for it: 19. Looks like a bug in OpenSSL.

**Comment by tomato42** [comment]
you're right, for group 7 (the 8192 bit one) generator is 19 while tlslite-ng has 5 hardcoded
