### ISSUE TITLE
Supports for ECDHE_ECDSA ciphers

### ISSUE THREAD

**Issue by phuslu** [tomato42/tlslite-ng#156]
Thanks for tlslite-ng works. I build [requests-httpsproxy](https://pypi.python.org/pypi/requests-httpsproxy/) on top of it.

But I found that seems tlslite-ng does not support ECDHE_ECDSA ciphers yet.
i.e.
```
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
```

Any thoughts/plan about it? Thanks!

**Comment by tomato42** [comment]
there is a plan: #52, but no specific timeframe
