### ISSUE TITLE
test-unsupported-cuve-fallback.py: uses secp192r1

### ISSUE THREAD

**Issue by nmav** [tomato42/tlslite-ng#159]
This is not a universally unsupported curve. In fact gnutls supports this curve when run on debian, thus the debian part of the test suite would fail. Switching to secp160r1 or even secp128r1 would address this for gnutls at least.

**Comment by tomato42** [comment]
either changed to secp160r1 or parametrised

**Comment by tomato42** [comment]
Wrong project :) please file against [tomato42/tlsfuzzer](https://github.com/tomato42/tlsfuzzer)

**Comment by nmav** [comment]
sorry :)
