### ISSUE TITLE
Invalid syntax in python 3.7

### ISSUE THREAD

**Issue by postlund** [tomato42/tlslite-ng#214]
Python 3.7 seems to be more strict about reserved keywords than earlier, yielding in an error due to "async" being used as a keyword argument:

```
.tox/py37/lib/python3.7/site-packages/tlslite/__init__.py:27: in <module>
    from tlslite.api import *
.tox/py37/lib/python3.7/site-packages/tlslite/api.py:11: in <module>
    from .tlsconnection import TLSConnection
E     File "/home/travis/build/postlund/pyatv/.tox/py37/lib/python3.7/site-packages/tlslite/tlsconnection.py", line 112
E       async=False):
E           ^
E   SyntaxError: invalid syntax
```

So the parameter must be renamed in order to work with python 3.7. I can create a PR for it, but since it's part of the API it might break for people using it. Any objections otherwise?

I assume that there's no offical support for python 3.7, but it will probably just work. A suggestion is to add python 3.7-dev to travis and see what happens.

**Comment by tomato42** [comment]
you're correct in the 3.7 support not being there because 3.7 is still in development, in general we plan to support all future versions

changing keyword names indeed is a (soft) API break so it's best not to do it

so I'm rather torn here, but I don't see any other option than to rename them, probably to `async_`, to minimise disruption

please prepare PR for it

**Comment by tomato42** [comment]
actually, I wonder if it wouldn't be possible to support it with `**kwargs` magic to not break backwards compatibility

**Comment by postlund** [comment]
I've read up a bit and it seems like async/await are reserved keywords, like "def" for instance. Made a small test and it's not possible to pass def as a keyword argument (through `**kwargs`) - it too yielded a syntax error - so I would assume that async is the same.

So I went with `async_` and did some other changes related to python 3.7. I'm not saying that we should merge this yet as python 3.7 is still in development, but lets start here to see if anything else pops up that needs to be fixed. It's good to be ahead.

https://github.com/tomato42/tlslite-ng/pull/216

**Comment by tomato42** [comment]
> Made a small test and it's not possible to pass def as a keyword argument (through **kwargs) - 
> it too yielded a syntax error - so I would assume that async is the same.

but you specify the name in `kwargs` as a string, not a token, so it can be anything. Yes, it won't work in 3.7, but it will in 3.6 and earlier, and that's the point

example code:
```
import warnings

def old(a, async=None):
    print(async)

def test(a, *args, async_=None, **kwargs):
    if args:
        async_ = args[0]
    if "async" in kwargs:
        warnings.warn("'async' is a keyword in Python 3.7, use 'async_'",
                      DeprecationWarning)
        async_ = kwargs["async"]
    print(async_)


print("regular:")
old('aa')
test('aa')

print("positional:")
old('aa', 'aa')
test('aa', 'aa')

print("new syntax:")
test('aa', async_='aa')

print("old syntax:")
old('aa', async='aa')
test('aa', async='aa')
```

**Comment by postlund** [comment]
> but you specify the name in kwargs as a string, not a token, so it can be anything

I would say that it's not the whole truth as only valid keyword names can appear as keys in kwargs. So you would never see for instance `def` or `1234` as keys since it's not possible to call a method using those identifers as keyword arguments. That's the point I was trying to make.

> Yes, calling it with async as parameter won't work in 3.7 (as interpreter will flip out), but it will in 3.6 and earlier, and that's the point

 My only point is that in python 3.7 it's not longer possible to use `async` as an argument name, even when using `**kwargs`. So the parameter must be renamed in order to have a consistent API across python versions. That it works in python 3.6 and earlier I assumed was obvious since it works as a positional argument today.

Do you want me to add the `async_deprecated` method as well to the PR?

**Comment by tomato42** [comment]
> My only point is that in python 3.7 it's not longer possible to use async as an argument name, even when using `**kwargs`

the following works just fine in python 3.6:
```
def test(*args, **kwargs):
    print(kwargs.get('def', None))

test()
args = {'def': "it works"}
test(**args)
```

> Do you want me to add the `async_deprecated` method as well to the PR?

yes, please. Preferably in a new module `tlslite/utils/deprecations.py`

**Comment by postlund** [comment]
> the following works just fine in python 3.6:

Ok, you are right 😄 I assume that the same would work in 3.7 as well, but not allowing the user to just specify it like test(async_=True) but using a dict doesn't seem like a very nice solution from an API-point-of-view.

> yes, please. Preferably in a new module tlslite/utils/deprecations.py

I'll make it happen and I'll fix the comments as well.

**Comment by tomato42** [comment]
That's not code from current master, this is:
https://github.com/tlsfuzzer/tlslite-ng/blob/dabc18f44bdfde944549822c1e4365e2267cdec9/tlslite/tlsconnection.py#L69-L74

**Comment by david-kooi-dsi** [comment]
Okay thanks. Must have duplicate installations on my end.
