### ISSUE TITLE
String argument without an encoding error

### ISSUE THREAD

**Issue by RononDex** [tomato42/tlslite-ng#358]
I keep getting this error when trying to run a script that uses tlslite-ng on python 3.7:

  File "C:\Users\<User>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tlslite\utils\rsakey.py", line 80, in hashAndSign
    hashBytes = secureHash(bytearray(bytes), hAlg)
TypeError: string argument without an encoding

It seems that bytearray has a mandatory parameter "encoding" which should be set to for example "utf-8"

**Comment by tomato42** [comment]
all hashes are defined over arrays of bytes, not arrays of characters

if you are signing a document, you need to define how it is canonicalized and encoded before a signature is applied so that the person verifying the signature can repeat the process

**Comment by tomato42** [comment]
the doc string actually is already explicit about it:
https://github.com/tomato42/tlslite-ng/blob/401712ca8ea16093933991e67d39a344bc1dc627/tlslite/utils/rsakey.py#L64-L72

or to put it other way: it's the duty of the calling code to convert the `str` to `bytes`, `bytearray` or `memoryview`

**Comment by RononDex** [comment]
I am not sure I understand...
my code that crashes is:
```
resp, content = client.request(request_token_url, "POST")
```

The full stacktrace:
```
Traceback (most recent call last):
  File ".\jiraOAuth.py", line 70, in <module>
    resp, content = client.request(request_token_url, "POST")
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2\__init__.py", line 673, in request
    req.sign_request(self.method, self.consumer, self.token)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2\__init__.py", line 502, in sign_request
    self['oauth_signature'] = signature_method.sign(self, consumer, token)
  File ".\jiraOAuth.py", line 36, in sign
    signature = privatekey.hashAndSign(raw)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tlslite\utils\rsakey.py", line 80, in hashAndSign
    hashBytes = secureHash(bytearray(bytes), hAlg)
TypeError: string argument without an encoding
```

Then this would suggest its an issue with `client.request`?

**Comment by tomato42** [comment]
yes, looks like an issue in oauth2 – likely bad port from Python2 (where `str` == `bytes`)

**Comment by Padmahas** [comment]
Hello @tomato42,

I'm still getting the same error. I tried sending "request_token_url" in the form of "bytes" instead of "String". But still getting the same error. If I send the "request_token_url" in the form of "bytearray" then I get an error saying, this method is expecting "bytes" instead of "bytearray".

What should be the correct fix for this?

Thank you.

**Comment by tomato42** [comment]
> What should be the correct fix for this?

fix oauth2 so that it doesn't pass in `str()` to `RSAKey.sign()`

**Comment by Padmahas** [comment]
> > What should be the correct fix for this?
> 
> fix oauth2 so that it doesn't pass in `str()` to `RSAKey.sign()`

Hey @tomato42 ,
Thank you for the reply. But I didn't get you correctly.
You mean, fix it in the "oauth2" library itself? OR is it something I have to do in my local code itself?

**Comment by tomato42** [comment]
> You mean, fix it in the "oauth2" library itself 

yes
