### ISSUE TITLE
Select certificate based on curves and ciphers too

### ISSUE THREAD

**Issue by tomato42** [tomato42/tlslite-ng#366]
After #196 is merged, it's possible to set-up multiple certificates, but the selection process is based
on signature_algorithms only.

The selection algorithm should also include ciphersuites and supported_groups in TLS 1.2 too.

**Comment by inikolcev** [comment]
@tomato42 So from what I can understand the decision process for selecting a certificate should go something like this:

1. Check if we offer a rsa cert, ecdsa cert or both.
2. If we offer both, offer all ciphersuites, otherwise filter them based on the certificate we have. 
3. Get the first cipher suite intersection and based on the ciphersuite decide what certificate to use.
4. If the client sends signature_algorithms, check that the certificate is signed with a sigalg supported by the client.
5. If the certificate is ECDSA, check that the curve in the public key is supported by the client
6. Select key exchange signature algorithm based on the certificate we offer.

Is this the way to go or am I missing something?

**Comment by tomato42** [comment]
> @tomato42 So from what I can understand the decision process for selecting a certificate should go something like this:
> 
>     1. Check if we offer a rsa cert, ecdsa cert or both.

actually, it's rsa, rsa-pss or ecdsa (now, later on it will also be dsa and eddsa) and we want to be able to have multiple certificates of the same type in the same virtual host
 
>     2. If we offer both, offer all ciphersuites, otherwise filter them based on the certificate we have.

yes, server needs to consider only ciphersuites that are compatible with certificates it has (side notes: TLS 1.3 ciphersuites are compatible with all certs except DSA; RSA key exchange is compatible with RSA certs only, it's not compatible with RSA-PSS certificates)

>     3. Get the first cipher suite intersection and based on the ciphersuite decide what certificate to use.
> 
>     4. If the client sends signature_algorithms, check that the certificate is signed with a sigalg supported by the client.

a). if the client didn't send sig_algs, it means we need to assume rsa+sha1, dsa+sha1 and ecdsa+sha1
b). we shouldn't abort connection just based on sig_algs, they should be used in advisory fashion
c). we should support sig_algs_cert
d). but the sig_alg_cert restriction applies not only to the server certificate but also to CA certificates (with exception of the signature on the self-signed root of trust) 
e). small RSA keys can't be used to sign using RSA-PSS+SHA512, smaller still can't do RSA-PSS+SHA384
f). in TLS 1.3 sig_algs for ecdsa also put a requirement on the curve used in EE certificate (i.e. P-256 curve can be used only with SHA-256)
 
>     5. If the certificate is ECDSA, check that the curve in the public key is supported by the client

yes, in TLS 1.2 and earlier

>     6. Select key exchange signature algorithm based on the certificate we offer.
> 
> 
> Is this the way to go or am I missing something?

if it turns out we can't use the selected ciphersuite because all the certificates we have are incompatible with supported_groups and/or sig_algs, then we need to retry with a different ciphersuite; the algorithm needs to support backtracking

and if we can't select a cert and ciphersuite while keeping all requirements, we shouldn't abort but rather ignore some requirements (definitely signatures in the certificate chain can be ignored, or curves used in the CA and intermediate CA certificates)

finally, the TLS doesn't force the server to select certificates and ciphersuite using any particular algorithm, that is, we don't have to select a cipher suite as the first step, we can select certificate first, and then based on that cert select a ciphersuite
