### ISSUE TITLE
Possible to enumerate list of ciphers without tearing down socket?

### ISSUE THREAD

**Issue by ajwstl** [tomato42/tlslite-ng#383]
My goal is to get a full list of supported protocols and ciphers for a given network endpoint and port.

Using `handshakeClientCert`, is there a way to force renogiatation of protocol and/or cipher without the relatively expensive operation of tearing down the socket connection and re-establishing same?

I wasn't able to find this in the docs, and looking through the code I remain uncertain if this is implemented in tlslite-ng for client-side TLS connections to a remote server.

**Comment by tomato42** [comment]
so, while it would be possible to do scanning of supported ciphers by renegotiating connections over and over, a). most servers have client initiated renegotiation disabled (if they support it at all), b). there is no renegotiation in TLS 1.3, so scanning that protocol like this is not possible, c). renegotiation is not supported in tlslite-ng (the underlying code can do it, as can be seen in [test-legacy-renegotiation.py](https://github.com/tomato42/tlsfuzzer/blob/master/scripts/test-legacy-renegotiation.py) in [tlsfuzzer](https://github.com/tomato42/tlsfuzzer) it's just the tlslite-ng tlsconnection that is intentionally limited as it's fairly hard to do securely)

btw: I have started to update [mozilla/cipherscan](https://github.com/mozilla/cipherscan) to use tlslite-ng for testing supported TLS features in servers, see [cscan.py](https://github.com/mozilla/cipherscan/blob/master/cscan.py) and [cscan](https://github.com/mozilla/cipherscan/tree/master/cscan) module

**Comment by ajwstl** [comment]
Thanks for the info and link to cipherscan, tomato42! Closing.
