### ISSUE TITLE
LocalAlert: unexpected_message: Expecting server_key_exchange, got certificate

### ISSUE THREAD

**Issue by martyur** [tomato42/tlslite-ng#399]
Have configured tls to produce a common signature ,but get an error during handshake. 

```Modules.tlslite.errors.TLSLocalAlert: unexpected_message: Expecting server_key_exchange, got certificate```

``` 
    settings.minVersion = (3,1)
    settings.maxVersion = (3,1)
    conn.handshakeClientCert(serverName=kwargs.get('server_hostname'), alpn=[b'http/1.1'], settings=settings)
    conn.getpeercert = functools.partial(tlslite_getpeercert, conn)```

**Comment by tomato42** [comment]
did you close this issue because you solved the problem?
