### ISSUE TITLE
How to use the StatusRequestExtension as a client

### ISSUE THREAD

**Issue by kkotowick** [tomato42/tlslite-ng#402]
I'm trying to figure out how to open a TLS connection with a ClientHello that includes the `StatusRequestExtension`. I can't seem to find a way to accomplish this though, as there doesn't seem to be any use of the `StatusRequestExtension `(or the related `CertificateStatusExtension`) in the codebase. i.e. there's no setting to enable this extension.

I've tried adding the extension directly by editing the source, but then I'm getting an error as follows:

> tlslite.errors.TLSLocalAlert: unexpected_message: Expecting server_key_exchange, got certificate_status

And from reviewing the source, it seems like the library is not capable of handling a `certificate_status` message from the server? i.e. the `HandshakeType.certificate_status` enum isn't actually used anywhere for an acceptable message type.

Any tips on this, or am I just spinning my wheels because it's not implemented?

**Comment by tomato42** [comment]
It's not implemented, see #60 , closing as duplicate

the classes are there because they are used by [tlsfuzzer](https://github.com/tomato42/tlsfuzzer)

the alert is generated because not only the extension needs to be sent, but the state machine needs to be updated to expect the new messages if the server replies with extension of its own

check the patch that adds TLS 1.3 session tickets for a template of the necessary changes

**Comment by BRK0014** [comment]
@kkotowick  Did you solve this by any chance?

Trying to use the StatusRequestExtension myself for client and am getting:

`tlslite.errors.TLSLocalAlert: unexpected_message: Expecting server_key_exchange, got certificate_status`

however if i set status_type to anything else than 1 (ocsp), it works.

Thanks

**Comment by tomato42** [comment]
no, it's not implemented: #61

**Comment by BRK0014** [comment]
> no, it's not implemented: #61

Are you looking to implement it?

**Comment by tomato42** [comment]
> > no, it's not implemented: #61
> 
> Are you looking to implement it?

not any time soon, the high priority items are in https://github.com/tomato42/tlslite-ng/milestone/5 and https://github.com/tomato42/tlslite-ng/milestone/7

that being said, if you just want to be able to get the OCSP from the server then the implementation is not too complex, you have to add flags to connection state to expect it in message rocessing and later save it in the session object

**Comment by BRK0014** [comment]
> > > no, it's not implemented: #61
> > 
> > 
> > Are you looking to implement it?
> 
> not any time soon, the high priority items are in https://github.com/tomato42/tlslite-ng/milestone/5 and https://github.com/tomato42/tlslite-ng/milestone/7
> 
> that being said, if you just want to be able to get the OCSP from the server then the implementation is not too complex, you have to add flags to connection state to expect it in message rocessing and later save it in the session object

Love the good work you guys doing! Thanks for everything

That sound complicated haha, i will try my best to see if i can do that :)!  have a nice day !

Is there any way to get in touch with you outside of github ?

**Comment by tomato42** [comment]
> Is there any way to get in touch with you outside of github ?

yes, email, though I prefer github issues as partial implementations or discussion of acceptable solutions are then available to everybody

**Comment by BRK0014** [comment]
> > Is there any way to get in touch with you outside of github ?
> 
> yes, email, though I prefer github issues as partial implementations or discussion of acceptable solutions are then available to everybody

Understandable, where could i find your email?

**Comment by tomato42** [comment]
third paragraph of readme: hkario at redhat.com
