### ISSUE TITLE
Not working server/client X509 example scheme

### ISSUE THREAD

**Issue by jaimesaez97** [tomato42/tlslite-ng#403]
Good afternoon.

I am trying to execute the X509 client/server described in `README.md` but I am receiving a `tlslite.errors.TLSAbruptCloseError: TLSAbruptCloseError()`.

This is the steps I am taking:
```
SERVER: $ python tls.py server -k <path_to_X509_key> -c <path_to_X509_cert> localhost:4443
CLIENT: $ python tls.py client localhost:4443
```

I print here the output:

![TLSlite-SERVER](https://user-images.githubusercontent.com/33544051/80215391-aacddf80-863c-11ea-84fd-a3ca6d72ab0b.png)
![TLSlite-CLIENT](https://user-images.githubusercontent.com/33544051/80215486-d355d980-863c-11ea-816d-9e3d034cd995.png)

Do you know which may be the error?

Best Regards,
Jaime.

**Comment by tomato42** [comment]
The connection negotiates RSA-PSS signatures but the key you're trying to use is too small for them. Try again with 2048bit RSA keys (IIRC 1024 bit will work also if you disable SHA-512 signatures)
