### ISSUE TITLE
Troubles when introduce new extension on ClientHello

### ISSUE THREAD

**Issue by jaimesaez97** [tomato42/tlslite-ng#404]
Hello.

I am trying to introduce a new APPLICATION_ID extension into ClientHello message.
I have added the extension QkdApplicationIdExtension into tlsextensions.py script, but I am getting an error when receiving ClientHello on server side.

* In `_handshakeClientAsyncHelper` function, I call `self._clientSendClientHello` with an extra parameter: the QKD_ID that I want to introduce. Also, in `settings` I have introduced a new field called `qkd_psk` to carry the application ID. 
* In `_clientSendClientHello` function, the ClientHello message creation is performed in a correct way, but when the message is sent through `_sendMsg` something **does not work correctly**.
    * **I think it is on `buf = msg.write()` statement**.
* In `_handshakeServerAsyncHelper` function, whene ClientHello is retrieved from `_serverGetClientHello` function, the message does not contains the QkdApplicationIdExtension.

I think the problem is in the message generation through a bytearray.

Could you help me?

Thank you very much.

**Comment by tomato42** [comment]
> does not work correctly.
> *  I think it is on buf = msg.write() statement.

that would suggest serialisation being incomplete; every extension needs to inherit from `TLSExtension` and implement at least the `extData` property and `parse` method (either directly or through inheritance, as you can see in the example below

> Could you help me?

without code it's hard to do, I'm also not familiar with this extension

there are multiple things that need to be updated to fully support an extension

the closest thing to help I can offer is suggest to look at PR #338, more specifically commits e7de0ff762e, 82b2cf2d65c, 82bba8b1259aa, and b3f8928a2737 there
