### ISSUE TITLE
Help in SMTP execution

### ISSUE THREAD

**Issue by jaimesaez97** [tomato42/tlslite-ng#417]
Hello.

I am having some problems in the SMTP client-server scheme execution.

I launch the server by this command:
```
python scripts/tls.py server -k tests/serverX509Key.pem -c tests/serverX509Cert.pem --max-ver tls1.3 localhost:4443
```

I launch the client by this script:
```
s = SMTP_TLS("www.google.es", port=4443)
s.ehlo()
s.starttls(x509Fingerprint="7e39be84a2e3a7ad071752e3001d931bf82c32dc")
```

But I do not receive any response.

If I change the host name **www.google.es** by the choosen on the example script **-------.net** it does not work because of the name, but with google as a host I do not receive any response.

What should I do?

Thank you,
Jaime.

**Comment by tomato42** [comment]
`tls.py server` does not implement SMTP
I'm also quite sure google doesn't serve SMTP on port 4443
If anything, they'd use port 25, 586 or 465, but I'd be surprised if that was on www.google.es server...
