### ISSUE TITLE
Support for Brainpool curves

### ISSUE THREAD

**Issue by pytz** [tomato42/tlslite-ng#428]
Hi,

first of all: thank you for this awesome project! I'm using it for TLS penetration testing and it is much easier to use than full fledges crypto libraries (e.g. OpenSSL or BouncyCastle).

During the testing I am now faced with the necessity to validate a certificate using the BrainpoolP256r1 curve. As far as I know this isn't supported yet. At least these curves aren't listed within CURVE_NAMES of handshakesettings.py. Nevertheless the used [ecdsa library](https://github.com/warner/python-ecdsa) seem to support these curves.

Are there any plans regarding the inclusion of brainpool curves in the future? Which steps or changes would be necessary to add support?

Thanks!

Version used: 0.8.0-alpha38

**Comment by tomato42** [comment]
> I'm using it for TLS penetration testing and it is much easier to use than full fledges crypto libraries (e.g. OpenSSL or BouncyCastle).

that's the primary use case so I'm glad you find it useful for it :)

> During the testing I am now faced with the necessity to validate a certificate using the BrainpoolP256r1 curve.

well, tlslite-ng doesn't check signatures in certificates, it only extracts the parameters from the certificate to verify the signatures...

> As far as I know this isn't supported yet. At least these curves aren't listed within CURVE_NAMES of handshakesettings.py.

yeah, they're not there, but I see that they are defined in the constants.py, and the code in X509 does use python-ecdsa to decode the OIDs, so I don't think there should be any big issues to make them work

try adding them to CURVE_NAMES, see what happens?

**Comment by pytz** [comment]
Thanks for the feedback. It was actually very easy to add the brainpool curves. Only like four placed had to be edited. I tried this before but using the master (0.8.0-alpha38) version I ran into an exception. But I might aswell have broken something else while trying to add the curves :)  
I started over and added the curves to ALL_CURVE_NAMES. This allows to use the curves but does not activate them by default. Adding them to CURVE_NAMES results in failed tests:

`
tlslite.errors.TLSLocalAlert: illegal_parameter: Client advertised in TLS 1.3 Client Hello a key exchange group forbidden in TLS 1.3
`

So they can be enabled on demand. I also added matching test cases and brainpool certificates. Creating a pull request now.

**Comment by tomato42** [comment]
yes, the exception is correct: use of brainpool curves is forbidden if you advertise TLS 1.3, it's an either-or situation

this configuration should be checked in HandshakeSettings() and we should abort then if they are used in combination
