### ISSUE TITLE
ECDSA support

### ISSUE THREAD

**Issue by tomato42** [tomato42/tlslite-ng#52]
Add support for ciphersuites that use ECDSA certificates

**Comment by jbremer** [comment]
I've observed the `TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA` ciphersuite while serving to `https://google.com/` on Internet Explorer 8 running on Windows 7.
What's your ETA on adding support for this family of ciphers?

**Comment by tomato42** [comment]
Yes, they are used "in the wild". Unfortunately I don't have an ETA for that, after 0.6.0 is released I will probably focus more on [tlsfuzzer](https://github.com/tomato42/tlsfuzzer).
