### ISSUE TITLE
Make constanttime module tests faster

### ISSUE THREAD

**Issue by tomato42** [tomato42/tlslite-ng#84]
Currently the [test_tlslite_utils_constanttime.py](https://github.com/tomato42/tlslite-ng/blob/master/unit_tests/test_tlslite_utils_constanttime.py) is running assertions against a large set of possible inputs, causing those tests to dominate overall unit test time.

The tests should be updated to use the `hypothesis` module for unit testing.

**Comment by The-Mule** [comment]
I would be interested in this issue, if you wouldn't mind, would you?

**Comment by tomato42** [comment]
that's *exactly* what "up-for-grabs" is for - to mark issues I don't plan to work next and would like to have fixed :smile:

**Comment by The-Mule** [comment]
omg, didn't I pull-requested this yet?? Am I on drugs or something? Let me do it immediately, it was so trivial change...

**Comment by tomato42** [comment]
:sweat_smile:

note that there are some small problems with new hypothesis on python 2.6 so travis tests will fail
